"""add description to products

Revision ID: 428c6b936bf3
Revises: a13d9d490f97
Create Date: 2022-01-20 12:16:31.418617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428c6b936bf3'
down_revision = 'a13d9d490f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
